# Generated by Django 2.2.2 on 2019-07-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190704_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/logo.png', help_text='Kapak Fotoğrafı Yükleyiniz.', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
