# Generated by Django 2.2.2 on 2019-07-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190705_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/logo.png', help_text='Kapak Fotoğrafı Yükleyiniz.', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
