# Generated by Django 2.2.2 on 2019-07-05 11:51

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190705_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[('yayin', 'YAYIN'), ('taslak', 'TASLAK')], default='yayin', max_length=6),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/logo.png', help_text='Kapak Fotoğrafı Yükleyiniz.', null=True, upload_to=blog.models.upload_to, verbose_name='Resim'),
        ),
    ]
