# Generated by Django 2.2.2 on 2019-07-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190705_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[(None, 'Lütfen Birini seçiniz '), ('yayin', 'YAYIN'), ('taslak', 'TASLAK')], max_length=6, null=True),
        ),
    ]
