# Generated by Django 2.2.2 on 2019-07-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190705_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[('all', 'Tümünü seç'), ('yayin', 'YAYIN'), ('taslak', 'TASLAK')], max_length=6, null=True),
        ),
    ]
