# Generated by Django 2.2.2 on 2019-07-08 14:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190705_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icerik',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='İçerik'),
        ),
    ]
