# Generated by Django 2.2.2 on 2019-07-09 08:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190708_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyisim')),
                ('email', models.EmailField(help_text='Bu alan zorunludur.', max_length=254, null=True, verbose_name='Email')),
                ('icerik', ckeditor.fields.RichTextField(help_text='Fikrinizi yazınız', max_length=1000, null=True, verbose_name='Yorum')),
                ('blog', models.ForeignKey(null=True, on_delete=True, to='blog.Blog')),
            ],
        ),
    ]
